name: GitHub Actions Demo
on: [push]
jobs:
  explore:
    runs-on: ubuntu-latest
    name: explore github action
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
        with: 
          ref: '${{github.ref}}'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Install packages
        run: yarn install
      - name: Build project
        run: npm run build
      - name: Start IPFS
        uses: ibnesayeed/setup-ipfs@master
        with:
          run_daemon: true
          ipfs_version: 0.8
      - name: Import keys and upload packages to IPFS
        id: ipfs
        run: |
          #Import IPNS Keys
          echo "::set-output name=shell-key::$(echo ${{ secrets.SHELL_IPNS_KEY }} | xxd -r -p | ipfs key import publish_shell -)"
          echo "::set-output name=wallet-key::$(echo ${{ secrets.WALLET_IPNS_KEY }} | xxd -r -p | ipfs key import publish_wallet -)"
          echo "::set-output name=provider-key::$(echo ${{ secrets.PROVIDER_IPNS_KEY }} | xxd -r -p | ipfs key import publish_provider -)"

          #Upload packages to IPFS
          echo "::set-output name=shell-hash::$(ipfs add -rQ ./packages/shell/public)"
          echo "::set-output name=wallet-hash::$(ipfs add -rQ ./packages/wallet/public)"
          echo "::set-output name=provider-hash::$(ipfs add -rQ ./packages/provider/dist)"
      - name: Check packages on public gateway
        run: |
          curl --write-out 'App Shell IPFS Status: %{http_code}\n' --silent --output /dev/null --fail http://localhost:8080/ipfs/${{ steps.ipfs.outputs.shell-hash }} & \
          curl --write-out 'Wallet IPFS Status: %{http_code}\n' --silent --output /dev/null --fail http://localhost:8080/ipfs/${{ steps.ipfs.outputs.wallet-hash }} & \
          curl --write-out 'Provider IPFS Status: %{http_code}\n' --silent --output /dev/null --fail http://localhost:8080/ipfs/${{ steps.ipfs.outputs.provider-hash }}

          curl --write-out 'App Shell IPFS Status: %{http_code}\n' --silent --output /dev/null --fail https://ipfs.io/ipfs/${{ steps.ipfs.outputs.shell-hash }} & \
          curl --write-out 'Wallet IPFS Status: %{http_code}\n' --silent --output /dev/null --fail https://ipfs.io/ipfs/${{ steps.ipfs.outputs.wallet-hash }} & \
          curl --write-out 'Provider IPFS Status: %{http_code}\n' --silent --output /dev/null --fail https://ipfs.io/ipfs/${{ steps.ipfs.outputs.provider-hash }}
      - name: Upload packages to IPNS
        run: |
          #Publish packages to IPNS
          ipfs name publish --key=publish_shell ${{ steps.ipfs.outputs.shell-hash }} & \
          ipfs name publish --key=publish_wallet ${{ steps.ipfs.outputs.wallet-hash }} & \
          ipfs name publish --key=publish_provider ${{ steps.ipfs.outputs.provider-hash }}
      - name: Check packages IPNS on public gateway
        run: |
          #Check package IPNS Status (on gateway)
          curl --write-out 'App Shell IPNS Status: %{http_code}\n' --silent --output /dev/null --fail https://ipfs.io/ipns/${{ steps.ipfs.outputs.shell-key }} &\
          curl --write-out 'Wallet IPNS Status: %{http_code}\n' --silent --output /dev/null --fail https://ipfs.io/ipns/${{ steps.ipfs.outputs.wallet-key }} & \
          curl --write-out 'Provider IPNS Status: %{http_code}\n' --silent --output /dev/null --fail https://ipfs.io/ipns/${{ steps.ipfs.outputs.provider-key }}