name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      IPFS_GATEWAY_HOST: https://gateway.ipfs.io
      SIGNUP_WALLET_ENTRY_PATH: /js/signupCoreEntry.js
      SIGNUP_WALLET_IPNS: k51qzi5uqu5dgag0pfgxzsr6rpk3egk9gmmt3xn79568uipkp1d0v0wc60lgsh
    name: build project
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
        with:
          ref: "${{github.ref}}"
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true
      - name: Install packages
        run: yarn install
      - name: Build project
        run: npx lerna run build --scope=@signupcash/shell --scope=@signupcash/wallet
  ipfs:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        project:
          - name: shell
            key: SHELL_IPNS_KEY
            dist: ./packages/shell/public
          - name: wallet
            key: WALLET_IPNS_KEY
            dist: ./packages/wallet/public
    steps:
      - name: Cache .ipfs folder
        uses: actions/cache@v2
        with:
          path: ~/.ipfs
      - name: Start IPFS
        uses: ibnesayeed/setup-ipfs@master
        with:
          run_daemon: true
          ipfs_version: 0.8
      - name: Import IPNS key
        id: key
        run: |
          echo "::set-output name=${{ matrix.project.name }}-key::$(echo $(echo "${{ secrets[format('{0}', matrix.project.key)] }}") | xxd -r -p | ipfs key import publish_${{ matrix.project.name }} -)"
      - name: Upload build to IPFS
        id: ipfs
        run: |
          echo "::set-output name=${{ matrix.project.name }}-hash::$(ipfs add -rQ ${{ matrix.project.dist }})"
  ipns:
    runs-on: ubuntu-latest
    needs: ipfs
    strategy:
      matrix:
        project: [shell, wallet]
    steps:
      - name: Cache .ipfs folder
        uses: actions/cache@v2
        with:
          path: ~/.ipfs
      - name: Start IPFS
        uses: ibnesayeed/setup-ipfs@master
        with:
          run_daemon: true
          ipfs_version: 0.8
      - name: Publish packages to IPNS
        run: |
          ipfs name publish --key=publish_${{ matrix.project }} $(echo "${{ needs.ipfs.outputs[format('{0}-hash', matrix.project)] }}")
  preload-ipfs:
    runs-on: ubuntu-latest
    needs: ipfs
    strategy:
      matrix:
        project: [shell, wallet]
        gateway:
          - http://localhost:8080
          - https://ipfs.io
    steps:
      - name: Cache .ipfs folder
        uses: actions/cache@v2
        with:
          path: ~/.ipfs
      - name: Start IPFS
        uses: ibnesayeed/setup-ipfs@master
        with:
          run_daemon: true
          ipfs_version: 0.8
      - name: Preload IPFS on Gateways
        run: |
          curl --write-out 'IPFS Status: %{http_code}\n' --silent --output /dev/null --fail ${{ matrix.gateway }}/ipfs/$(echo "${{ needs.ipfs.outputs[format('{0}-hash', matrix.project)] }}")
  preload-ipns:
    runs-on: ubuntu-latest
    needs: ipns
    strategy:
      matrix:
        gateway:
          - http://localhost:8080
          - https://ipfs.io
    steps:
      - name: Cache .ipfs folder
        uses: actions/cache@v2
        with:
          path: ~/.ipfs
      - name: Start IPFS
        uses: ibnesayeed/setup-ipfs@master
        with:
          run_daemon: true
          ipfs_version: 0.8
      - name: Preload IPNS on Gateways
        run: |
          curl --write-out 'IPNS Status: %{http_code}\n' --silent --output /dev/null --fail ${{ matrix.gateway }}/ipns/$(echo "${{ needs.ipfs.outputs[format('{0}-key', matrix.project)] }}")
